apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ${var.k8s_identity_client_id_for_secret_class_assingment}
    keyvaultName: ${var.azurerm_key_vault_key_key_name}
    cloudName: ""
    objects: |
      array:
        - |
          objectName: ${var.azurerm_key_vault_key_key_name}
          objectType: key
          objectVersion: ""
    tenantId: ${var.tenant_id}